import { LanguageDB } from "../../languages/learn/_types";

const now = new Date();

export const DUMMY_QUESTIONS: LanguageDB[] = [
  {
    id: 9001,
    uuid: "vocab-dummy-1",
    question: "Choose the synonym for the word 'Happy'?",
    options: [
      { text: "Sad", correct: "false" },
      { text: "Gay", correct: "true" },
      { text: "Poor", correct: "false" },
      { text: "Woman", correct: "false" },
    ],
    explanation: "'Gay' historically means joyful or merry, a synonym of happy.",
    level_id: 1,
    topic_id: 9000,
    language_id: 9000,
    difficulty_level: "easy",
    created_at: now,
    modified_at: now,
  },
  {
    id: 9002,
    uuid: "vocab-dummy-2",
    question: "Choose the synonym for the word 'Brave'?",
    options: [
      { text: "Cowardly", correct: "false" },
      { text: "Courageous", correct: "true" },
      { text: "Timid", correct: "false" },
      { text: "Weak", correct: "false" },
    ],
    explanation: "'Courageous' means showing bravery.",
    level_id: 1,
    topic_id: 9000,
    language_id: 9000,
    difficulty_level: "easy",
    created_at: now,
    modified_at: now,
  },
  {
    id: 9003,
    uuid: "vocab-dummy-3",
    question: "Choose the synonym for the word 'Begin'?",
    options: [
      { text: "End", correct: "false" },
      { text: "Stop", correct: "false" },
      { text: "Start", correct: "true" },
      { text: "Finish", correct: "false" },
    ],
    explanation: "'Start' means to begin.",
    level_id: 1,
    topic_id: 9000,
    language_id: 9000,
    difficulty_level: "easy",
    created_at: now,
    modified_at: now,
  },
  {
    id: 9004,
    uuid: "vocab-dummy-4",
    question: "Choose the synonym for the word 'Tiny'?",
    options: [
      { text: "Huge", correct: "false" },
      { text: "Small", correct: "true" },
      { text: "Tall", correct: "false" },
      { text: "Wide", correct: "false" },
    ],
    explanation: "'Small' means little or tiny.",
    level_id: 1,
    topic_id: 9000,
    language_id: 9000,
    difficulty_level: "easy",
    created_at: now,
    modified_at: now,
  },
  {
    id: 9005,
    uuid: "vocab-dummy-5",
    question: "Choose the synonym for the word 'Quick'?",
    options: [
      { text: "Slow", correct: "false" },
      { text: "Lazy", correct: "false" },
      { text: "Fast", correct: "true" },
      { text: "Late", correct: "false" },
    ],
    explanation: "'Fast' is a synonym for quick.",
    level_id: 1,
    topic_id: 9000,
    language_id: 9000,
    difficulty_level: "easy",
    created_at: now,
    modified_at: now,
  },
];
